version: 0.2
env:
  secrets-manager:
    SONAR_TOKEN: arn:aws:secretsmanager:eu-central-1:911845998067:secret:SonarCloud-7370vM:token
phases:
  pre_build:
    commands:
      - echo $SETTINGS > maven-deploy-settings.xml
      - cat maven-deploy-settings.xml
      - export REPOSITORY_TOKEN=$( aws codeartifact get-authorization-token --domain $CODEARTIFACT_DOMAIN_NAME --query authorizationToken --output text )
      - export BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/branch\///')
  build:
    commands:
      - env
      - echo "git status"
      - git status
      - echo "Build"
      - ./mvnw --settings maven-deploy-settings.xml -Dsmall.jar clean package
#        - echo "Deploy"
#        - ./mvnw --settings maven-deploy-settings.xml -Dsmall.jar -DaltDeploymentRepository=pn-codeartifact::default::https://${CODEARTIFACT_DOMAIN_FULL}/maven/${CODEARTIFACT_REPO}/ deploy
  post_build:
    commands:
      - echo "Sonar"
      - ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=pagopa -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=pagopa_pn-model
cache:
  paths:
    - $HOME/.m2
    - $HOME/.sonar