version: 0.2
env:
  secrets-manager:
    SONAR_TOKEN: arn:aws:secretsmanager:eu-central-1:911845998067:secret:SonarCloud-7370vM:token
phases:
  pre_build:
    commands:
      - echo $SETTINGS > maven-deploy-settings.xml
      - cat maven-deploy-settings.xml
  build:
    commands:
      - echo "Build"
      - ./mvnw --settings maven-deploy-settings.xml -Dsmall.jar clean package
      - ls target
  post_build:
    commands:
      - echo "Sonar"
      - ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=pagopa -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=pagopa_pn-model