version: 0.2
env:
  shell: bash
  secrets-manager:
    SONAR_TOKEN: arn:aws:secretsmanager:eu-central-1:911845998067:secret:SonarCloud-7370vM:token

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo $SETTINGS > maven-deploy-settings.xml
      - cat maven-deploy-settings.xml
      - export REPOSITORY_TOKEN=$( aws codeartifact get-authorization-token --domain $CODEARTIFACT_DOMAIN_NAME --query authorizationToken --output text )
      - export BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///')
      - export BRANCH_TARGET=$(echo $CODEBUILD_WEBHOOK_BASE_REF | sed 's/refs\/heads\///')
      - export PR_NUM=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/pr\///')
  build:
    on-failure: ABORT
    commands:
      - env
      - echo "Maven Build"
      - ./mvnw --settings maven-deploy-settings.xml -Dsmall.jar clean package
      - |
        if [[ "$BRANCH_NAME" =~ ^(main|develop)$ ]]; then
          echo "Deploy"
          ./mvnw --settings maven-deploy-settings.xml -Dsmall.jar -DaltDeploymentRepository=pn-codeartifact::default::https://${CODEARTIFACT_DOMAIN_FULL}/maven/${CODEARTIFACT_REPO}/ deploy
        fi
  post_build:
    on-failure: ABORT
    commands:
      - echo "Sonar"
      - |
        if [[ "$CODEBUILD_WEBHOOK_EVENT" == "PUSH" ]]; then
           SONAR_ADD_OPTS="-Dsonar.branch.name=$BRANCH_NAME -Dsonar.branch.target=$BRANCH_TARGET"
        else 
           SONAR_ADD_OPTS="-Dsonar.pullrequest.key=$PR_NUM -Dsonar.pullrequest.branch=$BRANCH_NAME -Dsonar.pullrequest.base=$BRANCH_TARGET"
        fi
      - ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar $SONAR_ADD_OPTS -Dsonar.organization=pagopa  -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=pagopa_pn-model

#reports:
#  - pn-model-junit-report:
# junit/jacoco

cache:
  paths:
    - $HOME/.m2
    - $HOME/.sonar