---
AWSTemplateFormatVersion: '2010-09-09'
Description: PR Pipeline
Parameters:
  GitHubProjectName:
    Description: Name of pagopa project name
    Type: String
    Default: pn-model
  CodeArtifactDomainName:
    Description: Used for maven repository access
    Type: String
    Default: pn-develop-bootstrap-step-01-domain
  CodeArtifactRepositoryName:
    Description: Used for maven repository access
    Type: String
    Default: pn-develop-bootstrap-step-01-repo
Resources:
  CodeBuildSourceCredential:
    Type: 'AWS::CodeBuild::SourceCredential'
    Properties:
      Token: '{{resolve:secretsmanager:github:SecretString:token}}'
      ServerType: GITHUB
      AuthType: PERSONAL_ACCESS_TOKEN
  CodeBuildProject:
    DependsOn: CodeBuildSourceCredential
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-CodeBuild"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
          - Name: CODEARTIFACT_DOMAIN_NAME
            Type: PLAINTEXT
            Value: !Sub "${CodeArtifactDomainName}"
          - Name: CODEARTIFACT_DOMAIN_FULL
            Type: PLAINTEXT
            Value:
              Fn::Join:
                - ''
                - - !Sub "${CodeArtifactDomainName}"
                  - !Sub '-${AWS::AccountId}.d.codeartifact.${AWS::Region}.${AWS::URLSuffix}'
          - Name: CODEARTIFACT_REPO
            Type: PLAINTEXT
            Value: !Sub "${CodeArtifactRepositoryName}"
          - Name: GITHUB_PRJ_NAME
            Type: PLAINTEXT
            Value: !Sub "${GitHubProjectName}"
          - Name: SETTINGS
            Type: PLAINTEXT
            Value: |
              <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
                <profiles>
                  <profile>
                    <id>pn-codeartifact</id>
                    <activation>
                      <activeByDefault>true</activeByDefault>
                    </activation>
                    <repositories>
                      <repository>
                        <id>pn-codeartifact</id>
                        <url>https://${env.CODEARTIFACT_DOMAIN_FULL}/maven/${env.CODEARTIFACT_REPO}/</url>
                      </repository>
                    </repositories>
                  </profile>
                </profiles>
                <servers>
                  <server>
                    <id>pn-codeartifact</id>
                    <username>aws</username>
                    <password>${env.REPOSITORY_TOKEN}</password>
                  </server>
                </servers>
              </settings>
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/pagopa/${GitHubProjectName}'
        BuildSpec: |
          version: 0.2
          env:
            shell: bash
            secrets-manager:
              SONAR_TOKEN: arn:aws:secretsmanager:eu-central-1:911845998067:secret:SonarCloud-7370vM:token
          phases:
            pre_build:
              on-failure: ABORT
              commands:
                - echo $SETTINGS > maven-deploy-settings.xml
                - cat maven-deploy-settings.xml
                - export REPOSITORY_TOKEN=$( aws codeartifact get-authorization-token --domain $CODEARTIFACT_DOMAIN_NAME --query authorizationToken --output text )
                - export BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///')
                - export BRANCH_TARGET=$(echo $CODEBUILD_WEBHOOK_BASE_REF | sed 's/refs\/heads\///')
                - export PR_NUM=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/pr\///')
                - export CI_PROFILE="$CODEBUILD_CI"
            build:
              on-failure: ABORT
              commands:
                - env
                - echo "Maven Build"
                - ./mvnw --settings maven-deploy-settings.xml clean package
                - |
                  if [[ "$BRANCH_NAME" =~ ^(main|develop)$ ]]; then
                    echo "Deploy"
                    ./mvnw --settings maven-deploy-settings.xml -DaltDeploymentRepository=pn-codeartifact::default::https://${CODEARTIFACT_DOMAIN_FULL}/maven/${CODEARTIFACT_REPO}/ deploy
                  fi
            post_build:
              on-failure: ABORT
              commands:
                - echo "Sonar"
                - |
                  if [[ "$CODEBUILD_WEBHOOK_EVENT" == "PUSH" ]]; then
                     SONAR_ADD_OPTS="-Dsonar.branch.name=$BRANCH_NAME -Dsonar.branch.target=$BRANCH_TARGET"
                  else 
                     SONAR_ADD_OPTS="-Dsonar.pullrequest.key=$PR_NUM -Dsonar.pullrequest.branch=$BRANCH_NAME -Dsonar.pullrequest.base=$BRANCH_TARGET"
                  fi
                - ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar $SONAR_ADD_OPTS -Dsonar.organization=pagopa -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=pagopa_${GITHUB_PRJ_NAME}
          cache:
            paths:
              - '/root/.m2/**/*'
              - '/root/.sonar/**/*'
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/(main|develop)$
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
            - Type: BASE_REF
              Pattern: ^refs/heads/(main|develop)$

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
              - Sid: BearerTokenPolicy
                Effect: Allow
                Action:
                  - sts:GetServiceBearerToken
                Resource: "*"
                Condition:
                  StringEquals:
                    'sts:AWSServiceName': codeartifact.amazonaws.com
              - Sid: GitHubSecret
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"
              - Sid: CodeArtifactGetAuthorizationTokenPolicy
                Effect: Allow
                Action:
                  - codeartifact:GetAuthorizationToken
                  - codeartifact:ReadFromRepository
                Resource: !Sub 'arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:repository/${CodeArtifactDomainName}/${CodeArtifactRepositoryName}'
  CodeBuildNotifications:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: FULL
      Name: !Sub '${GitHubProjectName}-msg'
      EventTypeIds:
        - codebuild-project-build-state-failed
      Resource: !Sub '${CodeBuildProject.Arn}'
      Targets:
        - TargetAddress:
            !ImportValue 'build-msg-topic'
          TargetType: SNS